'''
    Script to generate room plans and student ID check forms.

    Room plans are generated by distributing the student in their ID order over rooms.

    Assumptions:
    - The file teilnehmer.csv exists, and has the following format:
            lastname1;firstname1;studentid1
            lastname2;firstname2;studentid2
            ...
'''

import os, csv, shutil, sys

# The available rooms and the seat numbers to be used
n012 = range(18, 1, -2) + range(58, 39, -2) + range(98, 79, -2) + range(138, 119, -2) + \
       range(178, 159, -2) + range(218, 199, -2) + range(258, 239, -2)

n111 = range(16, 1, -2) + range(48, 33, -2) + range(80, 65, -2) + range(112, 97, -2)

n115 = range(26, 1, -2) + range(94, 61, -2) + range(162, 129, -2) + range(230, 197, -2) + \
       range(298, 265, -2) + range(366, 333, -2) + range(434, 401, -2) + range(502, 469, -2) + \
       range(570, 537, -2) + range(638, 605, -2) + range(706, 673, -2)

r305 = range(16, 1, -2) + range(48, 33, -2) + range(80, 65, -2) + range(112, 97, -2)

avail_rooms = (('N012', n012), ('N111', n111), ('N115', n115), ('305', r305))

# Determine exam rooms given on command line
rooms=filter(lambda room:(room[0] in sys.argv), avail_rooms)

# Read students from CSV file
students = []
with open('teilnehmer.csv', 'rb') as csvfile:
    reader = csv.reader(csvfile, delimiter=';')
    for row in reader:
        students.append((int(row[2]), row[1], row[0]))

# Build global room plan
students=sorted(students)
roomplan = open('roomplantable.tex','w')
roomentry = open('roomentrytable.tex','w')
current=0
roomplan.write("\\titleblock\\begin{multicols}{3}")
for room, seats in rooms:
    roomplan.write("\\vspace{1em}\\textbf{Raum %s}\n\n"%(room,))
    for seat in seats:
        if current<len(students):
            studentid, firstname, lastname =students[current]
            roomplan.write("%s - %s - Platz %.3u\\\\\n"%(studentid, room, seat))
            roomentry.write("%s & %s %s &  & %s (%.3u)\\\\\n"%(studentid, firstname, lastname, room, seat))
            current+=1
        else:
            break
roomplan.write("\\end{multicols}\n")
roomplan.close()
roomentry.close()
os.system('lualatex roomplan.tex')
os.system('lualatex roomentry.tex')

if current<len(students):
    print("\nWARNING: Not enough room for all students, %u left!\n"%(len(students)-current))

